# Generated by Django 3.2.3 on 2024-06-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance_app', '0002_alter_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentclearance',
            name='date_cleared',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departmentclearance',
            name='is_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
