# Generated by Django 3.2.3 on 2024-06-28 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clearance_app', '0004_alter_student_sex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
