# Generated by Django 3.2.3 on 2024-07-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance_app', '0006_document_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentclearance',
            name='file',
            field=models.FileField(default=1, upload_to='department-documents/'),
            preserve_default=False,
        ),
    ]
