# Generated by Django 3.2.3 on 2024-07-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance_app', '0007_departmentclearance_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentclearance',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
